sth/urls.py
from django.contrib import admin
from django.urls import path

# from django.http import HttpResponse

# # writing these functions here is so impractical and nonstandard!
# def projects(request):
#     return HttpResponse('Here are our products')

# def project(request, pk):
#     return HttpResponse(f'This is the project with id {pk}.')

from django.urls import include

# we need to add in a few things in this file(roor's urls.py) here
# so basically we just need to add a path to actually find those
# images

from django.conf import settings  # because we want to connect to our media root

# and our media url(MEDIA_URL and MEDIA_ROOT)
from django.conf.urls.static import static

# static is basically going to help us create a new URL for our static
# files

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('projects/', projects, name="projects"),
    # path('project/<str:pk>/', project, name="project"), # cool to know, but not very practical though, see urls.py under projects directory
    path("projects/", include("projects.urls")),  # '' means that's gonna be our root domain
    path("", include('users.urls')),
]

# go ahead and set a new URL path
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# recall that MEDIA_ROOT is where we send the user uploaded content and
# we just created a file path. So Django before did not know how to
# actually set that and we didn't have a url route for that. As you
# can see we just created that, we used the static method, we went into
# settings, grab the URL and connected it to MEDIA_ROOT and that also
# depends on the above urlpatterns as well (????)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# django still doesn't know how to serve these up
# we're gonna need a third party package called Django White Noise

users/urls.py
# This file wasn't automatically created by django, in fact
# we created it and we're gonna define urlpatterns just like
# before. Also recall that we have to include this in our
# main urls.py

from django.urls import path
# from django.urls.resolvers import URLPattern
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    
    path("", views.profiles, name='profiles'),
    path("profile/<str:pk>/", views.userProfile, name="user-profile")
]

projects/models.py
from django.db import models
import uuid

# from django.db.models.expressions import Value # what is this?!?

# Create your models here. These are generally our tables

"""Did you know after creating this class you have to run `python manage.py 
makemigrations`"""

from users.models import Profile


class Project(models.Model):  # we inherit from django's model.Model class
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL) # SET_NULL because we don't want to delete a profile just because of deleting a project
    title = models.CharField(max_length=200)  # a char field like VARCHAR
    # null to true means we can allow for empty string
    description = models.TextField(null=True, blank=True)
    # blank is for django, while null is for the database (confused?)
    # some links are pretty long
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg")
    # After some consideration, I figured out that I need this new field
    # beside other fields, it's totally fine. The only thing I should take care
    # of is to run a migration and letting django know that we're using this
    # field. Another funny thing is that when we upload an image into the
    # django for any specific project, we end up having that image right in our 
    # root directory(please go on and try it!), so how are we going to specifiy this
    # problem? check the settings.py
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    # a timestamp, whenever the instance is created just insert a timestamp for it
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(
        "Tag", blank=True
    )  # try unquoting this Tag and this will raise an error due to not defining the Tag variable
    # while by using single quotation marks will make this to search through the document to nail it
    # otherwise we might need to cut and paste the Tag class above this one!
    # note that the blank part means we don't need no education! I mean tag
    id = models.UUIDField(
        default=uuid.uuid4,  # this is encoding actually
        unique=True,
        primary_key=True,
        editable=False,
    )  # by default django's models.Model class will create an id for us!!

    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)

    def __repr__(self) -> str:
        return str(self.title)

    def __str__(
        self,
    ) -> str:  # We use this to have some identifiable representation for our data in our table in the admin panel
        return self.__repr__()


# we're using this to demonstrate the creating process of a relationship between tables


class Review(models.Model):
    VOTE_TYPE = (  # this is for the sake of making reviews rateable!
        ("up", "Up Vote"),
        ("down", "Down Vote"),
    )  # this will be used to create a drop-down list
    # owner =
    # whenever a project is deleted, what are we going to do with the children?
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    # models.SET_NULL whenever a project is deleted their reviews will be left alone and
    # the project  field right here will just be set to null
    # while CASCADE will delete all the reviews if a project is deleted
    body = models.TextField(null=True, blank=True)
    value = models.CharField(
        max_length=200, choices=VOTE_TYPE
    )  # choices makes the dropbox
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.name.capitalize()


# don't forget to use makemigrations (why?)
# also don't forget to add them in admin.py (why?)

users/models.py
import email
from operator import mod
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        null=True,
        blank=True,
        upload_to="profiles/",
        default="profiles/user-default.png",
    )
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        # # if we create a profile without a user we'regonna get an error
        # return str(self.user.username)
        return str(self.username)


class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return str(self.name)

# Recall that after creating models you have to makemigrations and migrate
# them, then in order to register them into the admin panel, you need
# to go the admin.py under the app's folder and register them

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Our registration form looks very ugly, so we're here to
# configure a few things


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        # this is our chance to customize it and then later on when
        # we style this, we will need custom classes on our input fields
        fields = ["first_name", "email", "username", "password1", "password2"]
        labels = {
            'first_name': "Name",
        }

users/views.py
from importlib.resources import path
from django.shortcuts import render
from .models import Profile
# We can get rid of the below UserCreationForm in the registerUser method
# and use this. (Why?) same functionality with modified fields
from .forms import CustomUserCreationForm 

# Create your views here.

# These are for authentications
from django.shortcuts import redirect
from django.contrib.auth import login, authenticate, logout

from django.contrib.auth.models import User

# This is for flash messages
from django.contrib import messages

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context=context)


def logoutUser(request):
    # this one is going to delete the session
    logout(request)
    messages.error(request, 'User was logged out.')
    return redirect('login')


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description__exact="")

    context = {'profile': profile, "topSkills": topSkills, "otherSkills": otherSkills}
    return render(request, 'users/user-profile.html', context=context)


# Don't name it login because it's defined in django's scope
def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('profiles')


    if request.method == 'POST':
        # print(request.POST)
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            # print('Username does not exist')
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)
        # This will take in the user and pass and it will make sure the
        # pass matches the username and it will return back either the user
        # instance or None

        if user:
            # login function is going to create a session for this user
            # in the database. Then it's also going to get that session
            # and it's going to add that into our browser's cookies
            login(request, user)
            # So if a user successfully logs in, let's go ahead and redirect
            # the user
            return redirect('profiles')
            # this is not very friendly, since it just redirects users back
            # to the home page! But what if a user was checking some page
            # and that page needs an authentication, so the user don't get
            # lost
        else:
            messages.error(request, "Username or password is incorrect")

    return render(request, 'users/login_register.html')
    # next we need to manage its routing

def registerUser(request):
    page = 'register'
    
    # It's not clean code putting imports here, but it's for 
    # educational purposes
    # from django.contrib.auth.forms import UserCreationForm
    # form = UserCreationForm()
    form = CustomUserCreationForm()


    # Basically a model form based around user and it's designed to
    # actually add a user to the database
    
    # Whenever a post method is sent, we can check 
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # this is just going to check that everything is correct
            # all the fields match up and no data has been manipulated
            # or anything like that -_-
            user = form.save(commit=False)
            # making all usernames lowercase
            user.username = user.username.lower()
            user.save()
            # Now that the user has officially been added to the database and
            # saved, let's go ahead and put a flash message here and let the
            # user now that the account was actually created

            messages.success(request, 'User account was created!')

            login(request, user)
            # this is gonna create a session-based token in the database
            # and it's gonna added to the cookies
            return redirect('profiles')
        else:
            messages.error(request, "An error has occurred during registration")

    context = {"page":page, "form": form}
    return render(request, 'users/login_register.html', context)

users/templates/users/login_register.html
{%extends 'main.html'%}

{%block content%}

{% if page == 'register' %}

<h1>Register User</h1>

<form method="POST" action="{% url 'register' %}">

    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="Register User" />

</form>

<p>Already have an account? Login <a href="{% url 'login' %}">here</a>.</p>

{% else %}

<form action="{% url 'login' %}" method="POST">

    {% csrf_token %}

    <input type="text" name="username" placeholder="Username" />
    <input type="password" name="password" placeholder="Enter password" />
    <input type="submit" name="Login" />

    <p>Don't have an account? Sign up <a href="{% url 'register' %}">here</a>.</p>
</form>

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="images/icon.svg" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form action="#" class="form auth__form">
        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="forgetpassword.html">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="signup.html">Sign Up</a>
      </div>
    </div>
  </div>

{%endif%}

{%endblock content%}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

          {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" 
                      alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro|slice:"30"}}</h5>
                  </div>
                </div>
                <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                <div class="dev__skills">
                  {% for skill in profile.skill_set.all|slice:"6" %}
                  {% if true %}
                  # You don't put () after all when you want to access children
                  {% endif %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

          
        </div>
      </div>
    </section>

  </main>
{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_stackoverflow %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">

              {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                    {{skill.description}}
                </p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">

                        {% for tag in project.tags.all %}
                        {% if true %}
                        # this is a many to many relationship so we don't need to use set :/
                        {% endif %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                        
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}